cloud:
  aws:
    region:
      static: ap-northeast-2
    s3:
      bucketName: ${S3_BUCKET_NAME}
    stack:
      auto: false
    credentials:
      instanceProfile: true
      accessKey: ${AWS_ACCESS_KEY}
      secretKey: ${AWS_SECRET_KEY}

spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL;
    driver-class-name: org.h2.Driver
    username:

  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  security:
    oauth2:
      client:
        registration:
          google:
            scope: profile, email
            client-id: ${GOOGLE_OAUTH2_CLIENT_ID}
            client-secret: ${GOOGLE_OAUTH2_CLIENT_SECRET}
  web:
    resources:
      static-locations: classpath:/static/, classpath:/public/, classpath:/resources/, classpath:/META-INF/resources/, file:/opt/files/

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

---
spring:
  profiles:
    include: local-env
    active: local
---
spring:
  config:
    activate:
      on-profile: local # local settings
      # on-profile: prod

  datasource:
    url: jdbc:mariadb://${DATABASE_URL}:3306/automl
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    hikari:
      connection-timeout: 900000
      idle-timeout: 900000
      max-lifetime: 1800000
      maximum-pool-size: 100
      minimum-idle: 5

  h2:
    console:
      enabled: false

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
