spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL;
    driver-class-name: org.h2.Driver
    username:

  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

---
spring:
  profiles:
    include: local-env
    active: local
---
spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:mariadb://${DATABASE_URL}:3306/automl
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    hikari:
      connection-timeout: 900000
      idle-timeout: 900000
      max-lifetime: 1800000
      maximum-pool-size: 100
      minimum-idle: 5
  h2:
    console:
      enabled: false

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
