cloud:
  aws:
    region:
      static: ap-northeast-2
    s3:
      bucketName: ${S3_BUCKET_NAME}
    stack:
      auto: false
    credentials:
      instanceProfile: true
      accessKey: ${AWS_ACCESS_KEY}
      secretKey: ${AWS_SECRET_KEY}

spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL;
    driver-class-name: org.h2.Driver
    username:

  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true # 생략 가능하나 직관적 명시를 위해 추가

  security:
    oauth2:
      client:
        registration:
          google:
            scope: profile, email
            client-id: ${GOOGLE_OAUTH2_CLIENT_ID}
            client-secret: ${GOOGLE_OAUTH2_CLIENT_SECRET}

  session:
    store-type: jdbc

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

---
spring:
  profiles:
    active: local
    include: local-env
