spring:
  h2:
    console:
      enabled: true
  profiles:
    include: oauth
  datasource:
    url: jdbc:h2:~/data/local/automl;MODE=MYSQL
    driver-class-name: org.h2.Driver
    username:

  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    show-sql: true
    hibernate:
      ddl-auto: none
