spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL;
    driver-class-name: org.h2.Driver
    username:

  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    show-sql: true
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true # 생략 가능하나 직관적 명시를 위해 추가

  security:
    oauth2:
      client:
        registration:
          google:
            scope: profile, email
            client-id: ${GOOGLE_OAUTH2_CLIENT_ID}
            client-secret: ${GOOGLE_OAUTH2_CLIENT_SECRET}

  session:
    store-type: jdbc

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
