name: build

on:
  pull_request:
    branches: [ "main" ]

jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: gradle
      - name: Gradle 권한 부여
        run: |
          chmod +x ./gradlew
      - name: Node 설치
        uses: actions/setup-node@v3
        with:
          node-version: 16.14.0
      - name: Gradle 초기화
        run: |
          ./gradlew clean
      - name: Gradle 테스트
        run: |
          ./gradlew test
      - name: 커버리지 codecov에 업로드
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./admin-server/build/reports/jacoco/test/jacocoTestReport.xml

      - name: Gradle 빌드
        run: |
          ./gradlew build --exclude-task test --scan --no-daemon
