name: ci

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
      - name: Gradle 권한 부여
        run: |
          chmod +x ./gradlew
      - name: Gradle 초기화 및 빌드
        run: |
          ./gradlew clean 
          ./gradlew build --exclude-task test --info
      - name: Gradle 테스트
        run: |
          ./gradlew test
      - name: ECR 로그인
#        if: github.ref == 'refs/heads/main'
        id: ecr-login
        uses: jwalton/gh-ecr-login@v1
        with:
          access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: ap-northeast-2
      - name: Docker 이미지 빌드
#        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v3
        with:
          push: false
          tags: ${{ steps.ecr-login.outputs.account }}.dkr.ecr.ap-northeast-2.amazonaws.com/automl-main-web
      - name: ECR 업로드
#        if: github.ref == 'refs/heads/main'
        uses: jwalton/gh-ecr-push@v1
        with:
          access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: ap-northeast-2
          direction: push
          local-image: ${{ steps.ecr-login.outputs.account }}.dkr.ecr.ap-northeast-2.amazonaws.com/automl-main-web
          image: ${{ steps.ecr-login.outputs.account }}.dkr.ecr.ap-northeast-2.amazonaws.com/automl-main-web:${{ github.sha }},
            ${{ steps.ecr-login.outputs.account }}.dkr.ecr.ap-northeast-2.amazonaws.com/automl-main-web:latest
