name: ci

on:
  push:
  pull_request:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
      - name: Gradle 권한 부여
        run: |
          chmod +x ./gradlew
      - name: Gradle 초기화 및 빌드
        run: |
          ./gradlew clean 
          ./gradlew build --exclude-task test
      - name: Gradle 테스트
        run: |
          ./gradlew test
