name: ci

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
      - name: Gradle 권한 부여
        run: |
          chmod +x ./gradlew
      - name: Gradle 초기화 및 빌드
        run: |
          ./gradlew clean 
          ./gradlew build --exclude-task test --info
      - name: 빌드 결과물 업로드
        uses: actions/upload-artifact@master
        with:
          name: gradle-build
          path: build
      - name: Gradle 테스트
        run: |
          ./gradlew test

  docker:
    needs: gradle
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      - name: ECR 로그인
        uses: jwalton/gh-ecr-login@v1
        with:
          access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: ap-northeast-2
      - name: 빌드 결과물 다운로드
        uses: actions/download-artifact@master
        with:
          name: gradle-build
          path: build
      - name: Docker 이미지 빌드
        run: |
          ./gradlew build
          docker build --tag app:${{ github.sha }} .
      - name: ECR 업로드
        uses: jwalton/gh-ecr-push@v1
        with:
          access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: ap-northeast-2
          direction: push
          local-image: app:${{ github.sha }}
          image: app:${{ github.sha }}, app:latest
