on:
  pull_request_target:
    types: [ labeled ]

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'safe to test')
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: gradle

      - name: Gradle 권한 부여
        run: |
          chmod +x ./gradlew
      - name: Gradle 초기화
        run: |
          ./gradlew clean
        env:
          MY_SECRET: '${{secrets.SONAR_TOKEN}}'
